name: Build Test And Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16.13.2
        uses: actions/setup-node@v2
        with:
          node-version: 'v16.13.2'
          cache: 'npm'
#      - run: npm build
#      - run: npm test
#      - run: npm lint
      - run: "Ö´ÐÐÍê±Ï"
